### ISSUE TITLE
Setup base tilemap

### ISSUE THREAD

**Issue by roboparker** [sailor-snouts/hey-you-porkachu#1]
one of the layers should have colliders enabled
We want dummy tiles for floor, wall, object, doorway

**Comment by sranderson** [comment]
- added demo tile set from: 
https://opengameart.org/content/16x16-indoor-rpg-tileset-the-baseline

- In the "demoscott" scene, used tile map layers to denote floor, wall, and decoration layers
- wall and wall decoration tile maps also have composite colliders, so adding/removing tiles from those tile maps will auto-adjust the colliders for ya!
